[profile.default]
test = "test"
out = "artifacts-forge"
# via_ir = true
optimizer = true
optimizer_runs = 5_000
gas-reports = ["*"]
solc-version = "0.8.20"
verbosity = 2
fs_permissions = [{ access = "read-write", path = "./deployed/"}]
